# Generated by Django 5.0.4 on 2024-08-06 22:05

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('use', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=10)),
                ('user_info', models.TextField()),
                ('purpose', models.TextField()),
                ('target_audience', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='businessdomains',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='myapp.newcampaign'),
        ),
        migrations.AlterField(
            model_name='newbusinessdomains',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newbusinesses', to='myapp.newcampaign'),
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
