# Generated by Django 5.0.4 on 2024-07-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessdomains',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newbusinessdomains',
            options={'managed': True},
        ),
    ]
