# Generated by Django 5.0.4 on 2024-06-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_businesses_alter_campaign_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDomains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=100)),
                ('campaign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='myapp.campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='Businesses',
        ),
    ]
