# Generated by Django 5.0.4 on 2024-06-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_businessdomains_delete_businesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdomains',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='myapp.campaign'),
        ),
    ]
