# Generated by Django 5.0.4 on 2024-08-13 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_businessdomains_domain_businessdomains_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdomains',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='businessdomains',
            name='url',
        ),
    ]
