# Generated by Django 5.0.4 on 2024-08-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_businessdomains_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdomains',
            name='domain',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='businessdomains',
            name='url',
            field=models.CharField(default='default_name', max_length=255),
        ),
    ]
