# Generated by Django 5.0.4 on 2024-09-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_businessdomains_domain_businessdomains_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdomains',
            name='content',
            field=models.TextField(default='None'),
        ),
    ]
